### ISSUE TITLE
analyze.log: UnicodeEncodeError

### ISSUE THREAD

**Issue by rhoerbe** [edushare-at/py-etd#23]
see jenkins@hal0 job #28

Traceback (most recent call last):
  File "/opt/bin/analyze_log.py", line 134, in <module>
    print ("\n".join(summary_texts))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe4' in position 60: ordinal not in range(128)

**Comment by thomaswar** [comment]
fixed
